"""add must_change_password

Revision ID: 008f64605c3b
Revises: 3c9fd49ea1ae
Create Date: 2026-09-26 15:12:27.675374

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '008f64605c3b'
down_revision: Union[str, Sequence[str], None] = '3c9fd49ea1ae'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('admin_users', sa.Column('must_change_password', sa.Boolean(), server_default='0', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('admin_users', 'must_change_password')
    # ### end Alembic commands ###
