"""Add passport_data

Revision ID: 3c9fd49ea1ae
Revises: 01a425b6bb74
Create Date: 2026-09-26 11:28:13.433961

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3c9fd49ea1ae'
down_revision: Union[str, Sequence[str], None] = '01a425b6bb74'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('complaints', sa.Column('passport_data', sa.String(length=20), nullable=True, comment='PII: Passport details (Series and Number)'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('complaints', 'passport_data')
    # ### end Alembic commands ###
